# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
latex: false
warnings_are_errors: false

#r_packages: # maybe needed
#  - ggimage

#r_github_packages:
#  - covr
after_success:
  - Rscript -e 'library(covr); codecov()'
