# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
cache: packages
latex: false
pandoc: false
warnings_are_errors: false

before_install:
  - sudo add-apt-repository -y ppa:opencpu/imagemagick
  - sudo apt-get update
  - sudo apt-get install -y libmagick++-dev

# Needed to avoid 'missing' install failure message.
r_packages:
#  - magick
  - ggimage

#r_github_packages:
#  - covr
after_success:
  - Rscript -e 'library(covr); codecov()'
